import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { SideMeny } from "@navikt/dinesykmeldte-sidemeny";
import { Accordion, Cell, Grid } from "@navikt/ds-react";
import { PageContainer } from "@navikt/dinesykmeldte-sidemeny";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageContainer navigation={<SideMeny test />}>
        <Grid>
          {Array.from(new Array(25).keys()).map((index) => (
            <Cell xs={12} key={index}>
              <Accordion>
                <Accordion.Item>
                  <Accordion.Header>
                    Fake Accordion {index + 1}
                  </Accordion.Header>
                  <Accordion.Content>Some content</Accordion.Content>
                </Accordion.Item>
              </Accordion>
            </Cell>
          ))}
        </Grid>
      </PageContainer>
    </div>
  );
};

export default Home;
