name: Build and publish library

on: push

permissions:
  packages: write
  contents: write

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[pages]')"
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/teamsykmelding-github-actions-workflows/actions/yarn-cached@main
        with:
          NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - run: yarn test
      - run: yarn lint
      - run: yarn build
      - run: yarn npm publish
        if: github.ref == 'refs/heads/main'
        working-directory: ./library
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  increment-version:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: navikt/teamsykmelding-github-actions-workflows/actions/yarn-cached@main
        with:
          NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Setup github connection for auth
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://github-actions[bot]:$NAV_DS_TOKEN@github.com/$GITHUB_REPOSITORY.git
      - run: yarn version -i patch
        working-directory: ./library
      - run: git add . && git commit -m "[skip ci] bump version to $(jq -r .version library/package.json)" && git push
